### ISSUE TITLE
MathJax support

### ISSUE THREAD

**Issue by asterixpound** [rothsandro/eleventy-notes#37] opened 2023-10-11 14:26 UTC
For me, it is important in a note-taking application to have support for mathematical equations.

I tried adding [eleventy-plugin-mathjax](https://github.com/tsung-ju/eleventy-plugin-mathjax) to my clone of eleventy-notes but I get the following error: 

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble writing to "dist/404.html" from "../.app/pages/404.njk" (via EleventyTemplateError)
[11ty] 2. Transform `mathjax` encountered an error when transforming ../.app/pages/404.njk. (via EleventyTransformError)
[11ty] 3. Can't find handler for document (via Error)
```

Any idea what might be going on here?

Is there interest in adding MathJax support to eleventy-notes by default?

**Comment by rothsandro** [comment] 2023-10-12 15:18
The error is caused by html attributes starting with a special char, like `:aria-label` and `@click` which are used for [Alpine](https://alpinejs.dev/). These are valid attribute names but for some reason mathjax cannot parse the HTML document if such attributes are present. You can report this problem on the MathJax repo and maybe they will fix it.

As a workaround you can use the longhand syntax of Alpine by replacing `:foo` with `x-bind:foo` and `@bar` with `x-on:bar`. It works if the colon is in the middle and not at the beginning. Here is a [diff.patch](https://github.com/rothsandro/eleventy-notes/files/12884138/diff.patch) with the relevant changes. 

At the moment I don't have any plans to add MathJax by default.

**Comment by asterixpound** [comment] 2023-10-12 19:40
Thanks for your help, @rothsandro. Your patch worked for me. With eleventy-plugin-mathjax installed, equations are now rendered correctly without error.

I have also shared the issue with eleventy-plugin-mathjax at <https://github.com/tsung-ju/eleventy-plugin-mathjax/issues/6>.

**Comment by rothsandro** [comment] 2023-10-14 05:42
Great, thanks for your feedback. I'll close this issue as MathJax should fix their parser.

**Closed by rothsandro** 2023-10-14 05:42 UTC

**Comment by synesthesia** [comment] 2023-11-08 20:36
For the benefit of other readers, an alternative is to use [markdown-it-mathjax3](https://github.com/tani/markdown-it-mathjax3) - I appreciate you have no plans to merge but could supply a PR if that is of use

**Comment by rothsandro** [comment] 2023-11-18 13:16
@synesthesia Thanks for the recommendation, good to know for other users 👍
I don't plan to add this to the template atm.
